[extend]
useDefault = true

[allowlist]
description = "Global allowlist"
paths = [
  '''node_modules''',
  '''package-lock\.json''',
  '''\.env\.example''',
  '''terraform\.tfvars\.example''',
  '''terraform/envs/''',
  '''\.tfvars$''',
]
