apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: theepicbook
  namespace: argocd
spec:
  project: cloudopshub
  source:
    repoURL: https://github.com/lakunzy7/CloudOpsHub.git
    targetRevision: main
    path: gitops/base
  destination:
    server: https://kubernetes.default.svc
    namespace: theepicbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
